import Link from 'next/link';
import { Shell, PageHeading } from '../components/Shell';

export default function Demo() {
  return (
    <Shell>
      <div className="sf-wrap sf-content">
        <p className="sf-alert" role="note">
          ILLUSTRATIVE DEMO · All numbers and examples below are fictional. This page does not
          receive or display real reports.
        </p>
        <PageHeading eyebrow="Platform preview" title="A record built with care.">
          A fictional example of private intake, a saved receipt, and the separate review and
          publication steps. The live dashboard shows actual saved totals.
        </PageHeading>
        <section className="classic-dashboard" aria-label="Fictional dashboard example">
          <div className="classic-dashboard-status">
            <span className="classic-record-label">SAMPLE DATA</span>
            <Link href="/">View the live dashboard</Link>
          </div>
          <div className="classic-metrics">
            {[
              [3, 'Sample reports received'],
              [1, 'Sample reports reviewed'],
              [0, 'Sample cases published'],
            ].map(([value, label]) => (
              <div key={label}>
                <strong>{value}</strong>
                <span>{label}</span>
              </div>
            ))}
          </div>
          <div className="classic-dashboard-grid">
            <article className="classic-panel">
              <div className="classic-panel-heading">
                <h2>EXAMPLE PUBLIC RECORD</h2>
                <span>FICTIONAL</span>
              </div>
              <div className="classic-empty">
                <h3>No sample case is ready for publication</h3>
                <p>
                  The example has one reviewed reporting identity. The default threshold is 100
                  distinct reviewed reporting identities, followed by an authorized publication
                  decision. Names, offices, narratives, and evidence from pending cases stay
                  private.
                </p>
              </div>
            </article>
            <article className="classic-panel">
              <div className="classic-panel-heading">
                <h2>EXAMPLE REPORT JOURNEY</h2>
                <span>ILLUSTRATIVE</span>
              </div>
              <ol className="classic-review-steps">
                <li>
                  <span>01</span>
                  <div>
                    <h3>Write an incident</h3>
                    <p>
                      A fictional reporter describes a routine application at an example district
                      office. Optional evidence is uploaded privately.
                    </p>
                  </div>
                </li>
                <li>
                  <span>02</span>
                  <div>
                    <h3>Confirm the save</h3>
                    <p>
                      The report and receipt are recorded together. A private tracking code is
                      issued only after a confirmed save.
                    </p>
                  </div>
                </li>
                <li>
                  <span>03</span>
                  <div>
                    <h3>Wait for review</h3>
                    <p>
                      Authorized staff must be configured before review can begin. A receipt does
                      not establish an allegation or promise a review date.
                    </p>
                  </div>
                </li>
              </ol>
            </article>
            <article className="classic-panel">
              <div className="classic-panel-heading">
                <h2>PRIVATE RECEIPT</h2>
                <span>EXAMPLE ONLY</span>
              </div>
              <div className="classic-receipt-guide">
                <h3>Keep the real code private.</h3>
                <p>
                  No working receipt is generated by this demo. The live form issues a private
                  capability for status checks without exposing the report text or attachments.
                </p>
                <Link className="classic-outline-button" href="/tracker">
                  Open report tracking
                </Link>
              </div>
            </article>
            <article className="classic-panel">
              <div className="classic-panel-heading">
                <h2>AVAILABLE GUIDANCE</h2>
                <span>FIVE LANGUAGES</span>
              </div>
              <div className="classic-receipt-guide">
                <h3>English · አማርኛ · Afaan Oromoo · ትግርኛ · Soomaali</h3>
                <p>
                  Audio can be stored as evidence. Automatic transcription, AI evidence
                  verification, SMS intake, and automatic agency referrals are not active.
                </p>
                <Link href="/faq">Read the reporting FAQ →</Link>
              </div>
            </article>
          </div>
        </section>
        <div className="sf-actions" style={{ marginTop: 32 }}>
          <Link className="sf-button" href="/report">
            File a real private report →
          </Link>
          <Link className="sf-button sf-secondary" href="/privacy">
            Read the privacy guide
          </Link>
        </div>
      </div>
    </Shell>
  );
}
