#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
#  SAFUU — One-Shot Setup Script  |  setup.sh
#  Run once on a fresh server:  sudo bash setup.sh
#  Generates all secrets, creates dirs, writes .env, installs dependencies
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

ok()   { echo -e "${GREEN}✅  $1${NC}"; }
warn() { echo -e "${YELLOW}⚠   $1${NC}"; }
err()  { echo -e "${RED}🚫  $1${NC}"; exit 1; }
step() { echo -e "\n${GREEN}━━━ $1 ━━━${NC}"; }

echo -e "${GREEN}"
echo "  ███████╗ █████╗ ███████╗██╗   ██╗██╗   ██╗"
echo "  ██╔════╝██╔══██╗██╔════╝██║   ██║██║   ██║"
echo "  ███████╗███████║█████╗  ██║   ██║██║   ██║"
echo "  ╚════██║██╔══██║██╔══╝  ██║   ██║██║   ██║"
echo "  ███████║██║  ██║██║     ╚██████╔╝╚██████╔╝"
echo "  ╚══════╝╚═╝  ╚═╝╚═╝      ╚═════╝  ╚═════╝ "
echo "  ሳፉ — Ethiopian Anti-Corruption Platform"
echo -e "${NC}"

# ── Check: must not run as root on production ─────────────────────────────────
if [[ $EUID -eq 0 ]]; then
  warn "Running as root. For production, create a dedicated user:"
  warn "  adduser --system --group safuu && chown -R safuu:safuu /opt/safuu"
fi

# ── Check: Node.js ────────────────────────────────────────────────────────────
step "Checking Node.js"
if ! command -v node &>/dev/null; then
  err "Node.js not found. Install: https://nodejs.org (requires >=18)"
fi
NODE_VER=$(node --version)
NODE_MAJOR=$(echo "$NODE_VER" | cut -d. -f1 | tr -d 'v')
if [[ "$NODE_MAJOR" -lt 18 ]]; then
  err "Node.js $NODE_VER found, but >=18 required"
fi
ok "Node.js $NODE_VER"

# ── Check: openssl ────────────────────────────────────────────────────────────
step "Checking openssl"
if ! command -v openssl &>/dev/null; then
  err "openssl not found. Install: sudo apt install openssl"
fi
ok "openssl found"

# ── Create directories ────────────────────────────────────────────────────────
step "Creating directories"
mkdir -p data logs
chmod 700 data     # Only owner can read/write data
chmod 755 logs
ok "data/ and logs/ created"

# ── Generate .env if not exists ────────────────────────────────────────────────
step "Generating environment configuration"

if [[ -f .env ]]; then
  warn ".env already exists — skipping secret generation"
  warn "Delete .env and re-run setup to regenerate all secrets"
else
  ENCRYPTION_MASTER_KEY=$(openssl rand -hex 32)
  ENCRYPTION_SALT=$(openssl rand -hex 16)
  DEDUP_SALT=$(openssl rand -hex 20)
  DASHBOARD_API_KEY=$(openssl rand -hex 32)
  JWT_SECRET=$(openssl rand -hex 32)
  ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '=/+' | head -c 32)

  cat > .env << EOF
# ════════════════════════════════════════════════════════════════════════
#  SAFUU Environment  |  Generated by setup.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
#  KEEP THIS FILE SECRET — never commit to git
# ════════════════════════════════════════════════════════════════════════

# ── Telegram ─────────────────────────────────────────────────────────────
# Get from @BotFather on Telegram → /newbot
TELEGRAM_BOT_TOKEN=REPLACE_ME_GET_FROM_BOTFATHER

# Private admin Telegram channel ID (starts with -100)
# Create channel → Add bot as Admin → get ID via @userinfobot
ADMIN_CHANNEL_ID=REPLACE_ME_ADMIN_CHANNEL_ID

# Set this in BotFather → API → Secret Token (for webhook mode):
TELEGRAM_WEBHOOK_SECRET=$(openssl rand -hex 32)

# ── AI Services ───────────────────────────────────────────────────────────
# Claude — from console.anthropic.com
ANTHROPIC_API_KEY=REPLACE_ME_ANTHROPIC_KEY

# OpenAI Whisper — from platform.openai.com
OPENAI_API_KEY=REPLACE_ME_OPENAI_KEY

# Hive Moderation — AI image detection (free trial at thehive.ai)
HIVE_AI_KEY=REPLACE_ME_HIVE_KEY

# ── Encryption (AUTO-GENERATED — do not change after first run) ───────────
ENCRYPTION_MASTER_KEY=${ENCRYPTION_MASTER_KEY}
ENCRYPTION_SALT=${ENCRYPTION_SALT}

# ── Deduplication (AUTO-GENERATED) ───────────────────────────────────────
DEDUP_SALT=${DEDUP_SALT}

# ── API / Auth (AUTO-GENERATED) ───────────────────────────────────────────
DASHBOARD_API_KEY=${DASHBOARD_API_KEY}
JWT_SECRET=${JWT_SECRET}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Dashboard allowed origin (CORS)
DASHBOARD_ORIGIN=https://yourdomain.com

# ── Ports ─────────────────────────────────────────────────────────────────
API_PORT=3001
SMS_PORT=3002

# ── SMS (Africa's Talking) ────────────────────────────────────────────────
AT_API_KEY=REPLACE_ME_AT_API_KEY
AT_USERNAME=safuu
AT_SMS_FROM=SAFUU
AT_WEBHOOK_SECRET=$(openssl rand -hex 32)

# ── Email (FEACC routing) ─────────────────────────────────────────────────
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=REPLACE_ME_EMAIL
SMTP_PASS=REPLACE_ME_APP_PASSWORD
FEACC_EMAIL=contact@feaccdars.gov.et
EOF

  chmod 600 .env  # Only owner can read
  ok ".env generated with auto-generated secrets"

  echo ""
  echo -e "${YELLOW}┌──────────────────────────────────────────────────────────┐${NC}"
  echo -e "${YELLOW}│  IMPORTANT: Edit .env and replace all REPLACE_ME_ values  │${NC}"
  echo -e "${YELLOW}│  Generated secrets are already set — don't change them     │${NC}"
  echo -e "${YELLOW}│                                                            │${NC}"
  echo -e "${YELLOW}│  ADMIN_PASSWORD for dashboard login: ${ADMIN_PASSWORD}  │${NC}"
  echo -e "${YELLOW}│  Save this password securely before continuing!            │${NC}"
  echo -e "${YELLOW}└──────────────────────────────────────────────────────────┘${NC}"
  echo ""
fi

# ── Install dependencies ──────────────────────────────────────────────────────
step "Installing Node dependencies"
npm install --production 2>&1 | tail -5
ok "Dependencies installed"

# ── Run tests ─────────────────────────────────────────────────────────────────
step "Running test suite"
if node test.js 2>&1; then
  ok "All tests passed"
else
  err "Tests failed — do not deploy until fixed"
fi

# ── Verify .env is complete ────────────────────────────────────────────────────
step "Validating environment file"
MISSING=()
for key in TELEGRAM_BOT_TOKEN ANTHROPIC_API_KEY OPENAI_API_KEY \
           ADMIN_CHANNEL_ID ENCRYPTION_MASTER_KEY DEDUP_SALT \
           DASHBOARD_API_KEY JWT_SECRET; do
  VAL=$(grep -E "^${key}=" .env 2>/dev/null | cut -d= -f2-)
  if [[ -z "$VAL" || "$VAL" == *"REPLACE_ME"* ]]; then
    MISSING+=("$key")
  fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
  warn "The following env vars need to be set in .env:"
  for k in "${MISSING[@]}"; do echo "    • $k"; done
  echo ""
  warn "Edit .env then re-run: node safuu-bot.js"
else
  ok "All required env vars are set"
fi

# ── Check PM2 ─────────────────────────────────────────────────────────────────
step "Checking PM2"
if command -v pm2 &>/dev/null; then
  ok "PM2 found: $(pm2 --version)"
else
  warn "PM2 not installed. Install for production:"
  warn "  npm install -g pm2"
fi

# ── Setup logrotate ───────────────────────────────────────────────────────────
step "Setting up log rotation"
LOGROTATE_CONF="/etc/logrotate.d/safuu"
if [[ -w /etc/logrotate.d ]]; then
  cat > "$LOGROTATE_CONF" << 'EOF'
/opt/safuu/logs/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    create 0640 safuu safuu
    postrotate
        pm2 reloadLogs 2>/dev/null || true
    endscript
}
EOF
  ok "Log rotation configured at $LOGROTATE_CONF"
else
  warn "Cannot write to /etc/logrotate.d — skip logrotate (not root?)"
fi

# ── Git safety ────────────────────────────────────────────────────────────────
step "Checking .gitignore"
if [[ -f .gitignore ]]; then
  if ! grep -q "^\.env$" .gitignore 2>/dev/null; then
    echo ".env" >> .gitignore
    warn ".env added to .gitignore"
  fi
  if ! grep -q "^data/" .gitignore 2>/dev/null; then
    echo "data/" >> .gitignore
    echo "logs/" >> .gitignore
    warn "data/ and logs/ added to .gitignore"
  fi
  ok ".gitignore configured"
else
  cat > .gitignore << 'EOF'
.env
data/
logs/
node_modules/
*.db
*.db-wal
*.db-shm
EOF
  ok ".gitignore created"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  SAFUU Setup Complete  🇪🇹${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Edit .env — fill in all REPLACE_ME_ values"
echo "  2. Install Nginx + Certbot:"
echo "     sudo apt install nginx certbot python3-certbot-nginx"
echo "  3. Copy safuu-nginx.conf to /etc/nginx/sites-available/safuu"
echo "     Update 'yourdomain.com' → your actual domain"
echo "     sudo ln -s /etc/nginx/sites-available/safuu /etc/nginx/sites-enabled/"
echo "     sudo certbot --nginx -d yourdomain.com"
echo "     sudo nginx -t && sudo systemctl reload nginx"
echo "  4. Generate DH params (takes ~5 min):"
echo "     sudo openssl dhparam -out /etc/nginx/dhparam.pem 4096"
echo "  5. Start all services:"
echo "     pm2 start ecosystem.config.js"
echo "     pm2 save && pm2 startup"
echo "  6. Test it:"
echo "     curl https://yourdomain.com/health"
echo ""
echo "  Safuu bot: https://t.me/SafuuEthBot"
echo "  FEACC hotline: 959"
echo ""
echo -e "  ${GREEN}ሙስናን ሪፖርት አድርጉ — Report corruption. Protect Ethiopia.${NC}"
echo ""
